import Head from "next/head";
import LoginComp from "@/components/loginComp";
import styles from "@/styles/Home.module.css";

export default function Login(props: any) {
  return (
    <>
      <Head>
        <title>Wallet Application | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={styles.signup}
        style={{
          display: "flex",
          flexDirection: "column",
        }}
      >
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            width: "350px",
            height: "812px",
          }}
        >
          <LoginComp />
        </div>
      </div>
    </>
  );
}
