import Head from 'next/head';
import SignupComp from '@/components/SignupComp';
import styles from '@/styles/Home.module.css';

export default function Signup() {
  return (
    <>
      <Head>
        <title>Wallet Application | Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={styles.signup}
        style={{
          display: 'flex',
          flexDirection: 'column',
        }}
      >
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            width: '350px',
            height: '812px',
          }}
        >
          <SignupComp />
        </div>
      </div>
    </>
  );
}
